
SET ROLE ems_owner;
BEGIN;

CREATE TABLE IF NOT EXISTS mart.dim_vital_type (
  vital_type_key   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vital_type_code  TEXT UNIQUE NOT NULL,   -- e.g., 'pain_score', 'spo2', 'gcs_eye'
  display_name     TEXT,                   -- friendly name for BI (optional)
  nemsis_element   TEXT,                   -- e.g., 'eVitals.27'
  is_pain_score    BOOLEAN DEFAULT FALSE,
  is_numeric       BOOLEAN,                -- usually numeric? (pain_score, sbp, spo2...)
  scale_family     TEXT,                   -- 'numeric' | 'faces' | 'ordinal' | 'text'
  notes            TEXT
);

-- Optional: constrain scale_family to known values
ALTER TABLE mart.dim_vital_type
  ADD CONSTRAINT dim_vital_type_scale_family_chk
  CHECK (scale_family IS NULL OR scale_family IN ('numeric','faces','ordinal','text'));

COMMENT ON TABLE  mart.dim_vital_type IS 'Lookup of vital measurement types (normalized from NEMSIS eVitals).';
COMMENT ON COLUMN mart.dim_vital_type.vital_type_code  IS 'Stable code used by ETL (snake_case); unique natural key.';
COMMENT ON COLUMN mart.dim_vital_type.display_name     IS 'Human-friendly label for reporting.';
COMMENT ON COLUMN mart.dim_vital_type.nemsis_element   IS 'Source NEMSIS element (e.g., eVitals.27).';
COMMENT ON COLUMN mart.dim_vital_type.is_pain_score    IS 'TRUE when this type represents a pain score reading.';
COMMENT ON COLUMN mart.dim_vital_type.is_numeric       IS 'TRUE when value_numeric normally applies for this type.';
COMMENT ON COLUMN mart.dim_vital_type.scale_family     IS 'Value interpretation: numeric/faces/ordinal/text.';

COMMIT;
RESET ROLE;
