-- 25_mart_dim_procedure_table_creation.sql (idempotent)
SET ROLE ems_owner;
BEGIN;

-- Minimal shell if missing
CREATE TABLE IF NOT EXISTS mart.dim_procedure (
  procedure_key    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  procedure_code   TEXT UNIQUE NOT NULL
);

-- Ensure all expected columns exist (safe to re-run)
ALTER TABLE mart.dim_procedure
  ADD COLUMN IF NOT EXISTS display_name     TEXT,
  ADD COLUMN IF NOT EXISTS nemsis_element   TEXT,
  ADD COLUMN IF NOT EXISTS procedure_category TEXT,
  ADD COLUMN IF NOT EXISTS is_airway        BOOLEAN,
  ADD COLUMN IF NOT EXISTS is_vascular_access BOOLEAN,
  ADD COLUMN IF NOT EXISTS is_medication    BOOLEAN,
  ADD COLUMN IF NOT EXISTS notes            TEXT;

-- Optional category constraint – adjust allowed values later if you want
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dim_procedure_category_chk'
      AND conrelid = 'mart.dim_procedure'::regclass
  ) THEN
    ALTER TABLE mart.dim_procedure
      ADD CONSTRAINT dim_procedure_category_chk
      CHECK (
        procedure_category IS NULL
        OR procedure_category IN (
          'airway','circulation','monitoring','medication','other'
        )
      );
  END IF;
END$$;

-- Comments
COMMENT ON TABLE  mart.dim_procedure IS
  'Lookup of procedure types/skills (normalized from NEMSIS eProcedures).';
COMMENT ON COLUMN mart.dim_procedure.procedure_code IS
  'Stable code used by ETL; unique natural key (usually from ImageTrend / NEMSIS).';
COMMENT ON COLUMN mart.dim_procedure.display_name IS
  'Human-friendly label for reporting (e.g., IV, IO, 12-lead ECG, CPAP, RSI).';
COMMENT ON COLUMN mart.dim_procedure.procedure_category IS
  'Broad category: airway, circulation, monitoring, medication, other.';
COMMENT ON COLUMN mart.dim_procedure.is_airway IS
  'TRUE for airway procedures (OPA, NPA, BVM, ETT, supraglottic, etc.).';
COMMENT ON COLUMN mart.dim_procedure.is_vascular_access IS
  'TRUE for IV/IO procedures.';
COMMENT ON COLUMN mart.dim_procedure.is_medication IS
  'TRUE when this row represents a medication administration procedure.';
COMMENT ON COLUMN mart.dim_procedure.nemsis_element IS
  'Source NEMSIS element (e.g., eProcedures.03).';

COMMIT;
RESET ROLE;
