-- 26_mart_fact_procedure_table_creation.sql (idempotent)
SET ROLE ems_owner;
BEGIN;

-- Dimension must exist; okay if it already does
CREATE TABLE IF NOT EXISTS mart.dim_procedure (
  procedure_key    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  procedure_code   TEXT UNIQUE NOT NULL
);

-- Main fact table
CREATE TABLE IF NOT EXISTS mart.fact_procedure (
    pcr_number          TEXT NOT NULL,
    procedure_key       INTEGER NOT NULL REFERENCES mart.dim_procedure(procedure_key),
    procedure_time      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    attempts            INTEGER,
    successful          TEXT,
    equipment_size      TEXT,
    complication_list   TEXT,
    patient_response    TEXT,
    procedure_authorization TEXT,
    authorizing_physician   TEXT,
    vascular_access_location TEXT,
    prior_to_ems        TEXT,
    crew_member_id      TEXT,
    performer_role      TEXT,
    procedure_description TEXT,
    last_modified       TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    -- natural key for ON CONFLICT (newer last_modified wins)
    CONSTRAINT pk_fact_procedure UNIQUE
        (pcr_number, procedure_key, procedure_time, attempts)
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS ix_fact_procedure_pcr
    ON mart.fact_procedure(pcr_number);

CREATE INDEX IF NOT EXISTS ix_fact_procedure_time
    ON mart.fact_procedure(procedure_time);

CREATE INDEX IF NOT EXISTS ix_fact_procedure_key
    ON mart.fact_procedure(procedure_key);

CREATE INDEX IF NOT EXISTS ix_fact_procedure_last_modified
    ON mart.fact_procedure(last_modified);

COMMENT ON TABLE mart.fact_procedure IS
'One row per procedure attempt per PCR (normalized from stage.procedures_stg). Local times; newer-wins via last_modified.';

COMMIT;
RESET ROLE;
